version: '2'

services:
  app:
    build: .
    links:
      - db
    env_file:
      - '.flaskenv'
    ports:
      - '5000:5000'

  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mbkg_admin
      MYSQL_PASSWORD: mbkg2020
      MYSQL_DATABASE: mybanking_db

